### PR TITLE
add history endpoints for shows and movies

### PR DESCRIPTION
**Pull request by ryanproud**

### CODE REVIEW

**Comment by UweTrottmann** [comment]
Thanks. Though as I already [said in a previous PR](https://github.com/UweTrottmann/trakt-java/pull/79#issuecomment-233112664) these methods [already exist on the `Users` service](https://github.com/UweTrottmann/trakt-java/blob/v5.8.0/src/main/java/com/uwetrottmann/trakt5/services/Users.java#L228-L295) (they are identical, use `me` as the username with OAuth to get a users data). :blush:

**Comment by ryanproud** [comment]
Does that endpoint work if the account is private?

**Comment by UweTrottmann** [comment]
Why should it not? Just make sure to set an OAuth access token for the 
private account or one that is friends with it.


Am 7. Februar 2018 4:03:10 nachm. schrieb Ryan Proud 
<notifications@github.com>:

**Comment by ryanproud** [comment]
It does seem to work.  Not sure I understand why the endpoints should not be added because the functionality is duplicated elsewhere.  I would think you would want to maximize the coverage of the documented endpoints.

**Pull request closed without merging**
