### PR TITLE
Add paging parameters to Recommendations for movies and shows

### PR DESCRIPTION
**Pull request by chrisbanes**
Allows paging and limiting of results

### CODE REVIEW

**Comment by UweTrottmann** [comment]
Thanks! Any objection to adding the parameters to the existing methods? 
Maintaining overloaded methods has been a nuisance in the past.

Am 16. August 2019 08:30:17 schrieb Chris Banes <notifications@github.com>:

**Comment by chrisbanes** [comment]
I'm happy to just update the existing methods. That is an API breaking change though?

**Comment by chrisbanes** [comment]
Updated the commit to just add the parameters to the existing methods

**Comment by UweTrottmann** [comment]
Thanks! Will be available with `6.3.0` coming up right now.

**Pull request merged**
