### PR TITLE
Add pagination query parameters to sync ratings endpoints

### PR DESCRIPTION
**Pull request by defhead**
Add pagination query parameters to sync ratings endpoints like discussed in #123

### CODE REVIEW

**Comment by UweTrottmann** [comment]
Thanks!

One of your new tests appears to fail (see Checks tab).

```
java.lang.AssertionError: 

Expected size: 2 but was: 1 in:
[com.uwetrottmann.trakt5.entities.RatedSeason@131ef10]
	at com.uwetrottmann.trakt5.services.SyncTest.test_ratingsSeasons_with_pagination(SyncTest.java:368)
```

**Comment by defhead** [comment]
Actually I was wondering how should I manage the test data. I noticed that the tests are connected to a real Trakt account. When I created this PR 5 days ago, sync/ratings/seasons was returning at least 4 entries, which allowed me to test this pagination (2 pages retrievals). Today it's returning only one entry.

What is the data policy in your tests?

**Comment by UweTrottmann** [comment]
I suggest to then remove the asserts where you can not guarantee that they will work because e.g. data changes. It's just pagination, so I wouldn't go overboard with too extensive testing.

**Comment by UweTrottmann** [comment]
Not checking the body at all is a little too drastic, but I guess this works as other tests do for ratings.

Thanks again! Will be available in the next update.

**Pull request merged**
