### PR TITLE
Missing stuff in entities

### PR DESCRIPTION
**Pull request by florianmski**
Ok, this should be good!
Sorry about that, pretty new to the pull request thing.

As I was saying in the previous PR, I don't think the SyncItems class behave correctly.
If I do something like this, movie1 will not be in syncItems anymore.
```java
SyncItems syncItems = new SyncItems();
syncItems.movies(movie1);
syncItems.movies(movie2);
```
And according to the [docs](http://docs.trakt.apiary.io/#reference/sync/add-ratings/add-new-ratings), it's possible to add episodes and seasons without having to put them in a show object.

### CODE REVIEW

**Comment by UweTrottmann** [comment]
Having seasons and episode was fine. The helper methods should just behave like you are setting the fields by assignment.  E.g. how they work now. 

Also, could you make sure that you actually rebase against dev of this repository? Looks like there are still some rogue commits.

**Comment by florianmski** [comment]
That's probably because my fork is forked from the old trakt-java made by Jake on which I made some change a long time ago.
Doesn't seem to have any nice way to handle [this case](http://stackoverflow.com/questions/5749246/how-do-i-change-which-github-project-i-forked-from#5749331).
Gonna delete my fork, fork your repo and PR again, sorry about that.
Or you could just cherry pick my commit?

**Comment by UweTrottmann** [comment]
It's probably best if you create a fork of this repository to work against. Otherwise you will have to repeat this on every future PR.

**Comment by florianmski** [comment]
Will do, thanks!

**Pull request closed without merging**
